INSERT INTO Cities(Name,Region) VALUES('Acre',1);
INSERT INTO Cities(Name,Region) VALUES('Afula',1);
INSERT INTO Cities(Name,Region) VALUES('Arad',1);
INSERT INTO Cities(Name,Region) VALUES('Ariel',1);
INSERT INTO Cities(Name,Region) VALUES('Ashdod',1);
INSERT INTO Cities(Name,Region) VALUES('Ashkelon',1);
INSERT INTO Cities(Name,Region) VALUES('Baqa-Jatt',1);
INSERT INTO Cities(Name,Region) VALUES('Bat Yam',1);
INSERT INTO Cities(Name,Region) VALUES('Beersheva',1);
INSERT INTO Cities(Name,Region) VALUES('Beit She''an',1);
INSERT INTO Cities(Name,Region) VALUES('Beit Shemesh',1);
INSERT INTO Cities(Name,Region) VALUES('Beitar Illit',1);
INSERT INTO Cities(Name,Region) VALUES('Bnei Brakh',1);
INSERT INTO Cities(Name,Region) VALUES('Dimona',1);
INSERT INTO Cities(Name,Region) VALUES('Eilat',1);
INSERT INTO Cities(Name,Region) VALUES('El''ad',1);
INSERT INTO Cities(Name,Region) VALUES('Giv''atayim',1);
INSERT INTO Cities(Name,Region) VALUES('Giv''at Shmuel',1);
INSERT INTO Cities(Name,Region) VALUES('Hadera',1);
INSERT INTO Cities(Name,Region) VALUES('Haifa',1);
INSERT INTO Cities(Name,Region) VALUES('Herzliya',1);
INSERT INTO Cities(Name,Region) VALUES('Hod HaSharon',1);
INSERT INTO Cities(Name,Region) VALUES('Holon',1);
INSERT INTO Cities(Name,Region) VALUES('Jerusalem',1);
INSERT INTO Cities(Name,Region) VALUES('Karmiel',1);
INSERT INTO Cities(Name,Region) VALUES('Kafr Qasim',1);
INSERT INTO Cities(Name,Region) VALUES('Kfar Saba',1);
INSERT INTO Cities(Name,Region) VALUES('Kiryat Ata',1);
INSERT INTO Cities(Name,Region) VALUES('Kiryat Bialik',1);
INSERT INTO Cities(Name,Region) VALUES('Kiryat Gat',1);
INSERT INTO Cities(Name,Region) VALUES('Kiryat Malakhi',1);
INSERT INTO Cities(Name,Region) VALUES('Kiryat Motzkin',1);
INSERT INTO Cities(Name,Region) VALUES('Kiryat Onou',1);
INSERT INTO Cities(Name,Region) VALUES('Kiryat Shmona',1);
INSERT INTO Cities(Name,Region) VALUES('Kiryat Yam',1);
INSERT INTO Cities(Name,Region) VALUES('Lod',1);
INSERT INTO Cities(Name,Region) VALUES('Ma''ale Adumim',1);
INSERT INTO Cities(Name,Region) VALUES('Ma''alot-Tarshiha',1);
INSERT INTO Cities(Name,Region) VALUES('Migdal HaEmek',1);
INSERT INTO Cities(Name,Region) VALUES('Modi''in Illit',1);
INSERT INTO Cities(Name,Region) VALUES('Modi''in',1);
INSERT INTO Cities(Name,Region) VALUES('Maccabim-Reut',1);
INSERT INTO Cities(Name,Region) VALUES('Nahariya',1);
INSERT INTO Cities(Name,Region) VALUES('Nazareth',1);
INSERT INTO Cities(Name,Region) VALUES('Nazareth Illit',1);
INSERT INTO Cities(Name,Region) VALUES('Nesher',1);
INSERT INTO Cities(Name,Region) VALUES('Ness Ziona',1);
INSERT INTO Cities(Name,Region) VALUES('Netanya',1);
INSERT INTO Cities(Name,Region) VALUES('Netivot',1);
INSERT INTO Cities(Name,Region) VALUES('Ofakim',1);
INSERT INTO Cities(Name,Region) VALUES('Or Akiva',1);
INSERT INTO Cities(Name,Region) VALUES('Or Yehuda',1);
INSERT INTO Cities(Name,Region) VALUES('Petach Tikva',1);
INSERT INTO Cities(Name,Region) VALUES('Qalansawe',1);
INSERT INTO Cities(Name,Region) VALUES('Ra''anana',1);
INSERT INTO Cities(Name,Region) VALUES('Rahat',1);
INSERT INTO Cities(Name,Region) VALUES('Ramat Gan',1);
INSERT INTO Cities(Name,Region) VALUES('Ramat HaSharon',1);
INSERT INTO Cities(Name,Region) VALUES('Ramla',1);
INSERT INTO Cities(Name,Region) VALUES('Rehovot',1);
INSERT INTO Cities(Name,Region) VALUES('Rishon LeZion',1);
INSERT INTO Cities(Name,Region) VALUES('Rosh HaAyin',1);
INSERT INTO Cities(Name,Region) VALUES('Safed',1);
INSERT INTO Cities(Name,Region) VALUES('Sakhnin',1);
INSERT INTO Cities(Name,Region) VALUES('Sderot',1);
INSERT INTO Cities(Name,Region) VALUES('Shaghur',1);
INSERT INTO Cities(Name,Region) VALUES('Shfar''am',1);
INSERT INTO Cities(Name,Region) VALUES('Tamra',1);
INSERT INTO Cities(Name,Region) VALUES('Tayibe',1);
INSERT INTO Cities(Name,Region) VALUES('Tel Aviv',1);
INSERT INTO Cities(Name,Region) VALUES('Tiberias',1);
INSERT INTO Cities(Name,Region) VALUES('Tira',1);
INSERT INTO Cities(Name,Region) VALUES('Tirat HaCarmel',1);
INSERT INTO Cities(Name,Region) VALUES('Umm al-Fahm',1);
INSERT INTO Cities(Name,Region) VALUES('Yavne',1);
INSERT INTO Cities(Name,Region) VALUES('Yehud-Monosson',1);
INSERT INTO Cities(Name,Region) VALUES('Yokneam',1);
