INSERT INTO Cities VALUES(1,'Acre');
INSERT INTO Cities VALUES(2,'Afula');
INSERT INTO Cities VALUES(3,'Arad');
INSERT INTO Cities VALUES(4,'Ariel');
INSERT INTO Cities VALUES(5,'Ashdod');
INSERT INTO Cities VALUES(6,'Ashkelon');
INSERT INTO Cities VALUES(7,'Baqa-Jatt');
INSERT INTO Cities VALUES(8,'Bat Yam');
INSERT INTO Cities VALUES(9,'Beersheva');
INSERT INTO Cities VALUES(10,'Beit She''an');
INSERT INTO Cities VALUES(11,'Beit Shemesh');
INSERT INTO Cities VALUES(12,'Beitar Illit');
INSERT INTO Cities VALUES(13,'Bnei Brakh');
INSERT INTO Cities VALUES(14,'Dimona');
INSERT INTO Cities VALUES(15,'Eilat');
INSERT INTO Cities VALUES(16,'El''ad');
INSERT INTO Cities VALUES(17,'Giv''atayim');
INSERT INTO Cities VALUES(18,'Giv''at Shmuel');
INSERT INTO Cities VALUES(19,'Hadera');
INSERT INTO Cities VALUES(20,'Haifa');
INSERT INTO Cities VALUES(21,'Herzliya');
INSERT INTO Cities VALUES(22,'Hod HaSharon');
INSERT INTO Cities VALUES(23,'Holon');
INSERT INTO Cities VALUES(24,'Jerusalem');
INSERT INTO Cities VALUES(25,'Karmiel');
INSERT INTO Cities VALUES(26,'Kafr Qasim');
INSERT INTO Cities VALUES(27,'Kfar Saba');
INSERT INTO Cities VALUES(28,'Kiryat Ata');
INSERT INTO Cities VALUES(29,'Kiryat Bialik');
INSERT INTO Cities VALUES(30,'Kiryat Gat');
INSERT INTO Cities VALUES(31,'Kiryat Malakhi');
INSERT INTO Cities VALUES(32,'Kiryat Motzkin');
INSERT INTO Cities VALUES(33,'Kiryat Onou');
INSERT INTO Cities VALUES(34,'Kiryat Shmona');
INSERT INTO Cities VALUES(35,'Kiryat Yam');
INSERT INTO Cities VALUES(36,'Lod');
INSERT INTO Cities VALUES(37,'Ma''ale Adumim');
INSERT INTO Cities VALUES(38,'Ma''alot-Tarshiha');
INSERT INTO Cities VALUES(39,'Migdal HaEmek');
INSERT INTO Cities VALUES(40,'Modi''in Illit');
INSERT INTO Cities VALUES(41,'Modi''in');
INSERT INTO Cities VALUES(42,'Maccabim-Reut');
INSERT INTO Cities VALUES(43,'Nahariya');
INSERT INTO Cities VALUES(44,'Nazareth');
INSERT INTO Cities VALUES(45,'Nazareth Illit');
INSERT INTO Cities VALUES(46,'Nesher');
INSERT INTO Cities VALUES(47,'Ness Ziona');
INSERT INTO Cities VALUES(48,'Netanya');
INSERT INTO Cities VALUES(49,'Netivot');
INSERT INTO Cities VALUES(50,'Ofakim');
INSERT INTO Cities VALUES(51,'Or Akiva');
INSERT INTO Cities VALUES(52,'Or Yehuda');
INSERT INTO Cities VALUES(53,'Petach Tikva');
INSERT INTO Cities VALUES(54,'Qalansawe');
INSERT INTO Cities VALUES(55,'Ra''anana');
INSERT INTO Cities VALUES(56,'Rahat');
INSERT INTO Cities VALUES(57,'Ramat Gan');
INSERT INTO Cities VALUES(58,'Ramat HaSharon');
INSERT INTO Cities VALUES(59,'Ramla');
INSERT INTO Cities VALUES(60,'Rehovot');
INSERT INTO Cities VALUES(61,'Rishon LeZion');
INSERT INTO Cities VALUES(62,'Rosh HaAyin');
INSERT INTO Cities VALUES(63,'Safed');
INSERT INTO Cities VALUES(64,'Sakhnin');
INSERT INTO Cities VALUES(65,'Sderot');
INSERT INTO Cities VALUES(66,'Shaghur');
INSERT INTO Cities VALUES(67,'Shfar''am');
INSERT INTO Cities VALUES(68,'Tamra');
INSERT INTO Cities VALUES(69,'Tayibe');
INSERT INTO Cities VALUES(70,'Tel Aviv');
INSERT INTO Cities VALUES(71,'Tiberias');
INSERT INTO Cities VALUES(72,'Tira');
INSERT INTO Cities VALUES(73,'Tirat HaCarmel');
INSERT INTO Cities VALUES(74,'Umm al-Fahm');
INSERT INTO Cities VALUES(75,'Yavne');
INSERT INTO Cities VALUES(76,'Yehud-Monosson');
INSERT INTO Cities VALUES(77,'Yokneam');
